language: node_js
node_js:
  - 0.10
os: linux
dist: xenial
before_install:
  - phantomjs --version
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    - "ichisadashioko@gmail.com"
