language: node_js
node_js:
  - 0.10
before_install:
  - phantomjs --version
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    - "ichisadashioko@gmail.com"
  irc:
    channels:
      - "irc.freenode.org#enchantjs"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
