name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [0.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Install dependencies
    - run: npm install -g grunt-cli@0.1.13
    - run: npm install

    - name: Build and run tests
      run: npm test

    # Create artifact
    - run: mkdir -p ../artifact
      # include all the examples and source code
    - run: rsync -av --progress . ../artifact --exclude node_modules --exclude .git

    # Show artifact structure
    - run: sudo apt install tree
    - run: tree ../artifact

    - name: Move artifact directory inside project directory to create artifact
      run: mv ../artifact ./

    - name: Compute commit short SHA
      id: shortsha
      run: echo "::set-output name=value::$(git rev-parse --short HEAD)"

    - uses: actions/upload-artifact@v2
      with:
        name: enchantjs-${{ steps.shortsha.outputs.value }}
        path: artifact
